
const fs = require('fs'); 

var REGISTRY_CONTRACT = "";
var BINDING_CONTRACT = "";
var TOKEN_CONTRACT = "";
var DEPLOYED_HEIGHT = 0;
var DEPLOYER_ADDRESS = "";

exports.REGISTRY_CONTRACT = REGISTRY_CONTRACT;
exports.BINDING_CONTRACT = BINDING_CONTRACT;
exports.TOKEN_CONTRACT = TOKEN_CONTRACT;
exports.DEPLOYED_HEIGHT = DEPLOYED_HEIGHT;
exports.DEPLOYER_ADDRESS = DEPLOYER_ADDRESS;
exports.SaveEnvConfig = SaveEnvConfig;

function SaveEnvConfig() {
  fs.writeFileSync(".env", 
    `REGISTRY_CONTRACT=${exports.REGISTRY_CONTRACT}
BINDING_CONTRACT=${exports.BINDING_CONTRACT}
TOKEN_CONTRACT=${exports.TOKEN_CONTRACT}
DEPLOYED_HEIGHT=${exports.DEPLOYED_HEIGHT}
DEPLOYER_ADDRESS=${exports.DEPLOYER_ADDRESS}
    `);
}